/* Пример 1: Создайте курсор, содержащий отсортированные по алфавиту фамилии учеников и названия их предметов, откройте его, выведите первую строку, закройте и освободите курсор */
DECLARE MyCursor CURSOR FOR SELECT Фамилия, Предмет FROM Ученики ORDER BY Фамилия OPEN MyCursor FETCH MyCursor CLOSE MyCursor DEALLOCATE MyCursor
/* Пример 2: Создайте курсор с прокруткой, содержащий список учеников, откройте его, выведите пятую, предыдущую, с конца четвертую, шесть позиций назад находящуюся, четыре позиций вперед находящуюся, следующую, первую, последнюю строку, закройте и освободите курсор */
DECLARE MyCursor CURSOR SCROLL FOR SELECT ID, Фамилия, Предмет, Школа, Баллы FROM Ученики OPEN MyCursor FETCH ABSOLUTE 5 FROM MyCursor FETCH PRIOR FROM MyCursor FETCH ABSOLUTE -4 FROM MyCursor FETCH RELATIVE -6 FROM MyCursor FETCH RELATIVE 4 FROM MyCursor FETCH NEXT FROM MyCursor FETCH FIRST FROM MyCursor FETCH LAST FROM MyCursor CLOSE MyCursor DEALLOCATE MyCursor
/* Пример 3: С помощью курсора, вычислите среднее арифметическое значение балла у учеников с наибольшим и наименьшим баллом */
DECLARE MyCursor CURSOR SCROLL FOR SELECT Баллы FROM Ученики ORDER BY Баллы DECLARE @S3 FLOAT = 0, @B3 FLOAT OPEN MyCursor FETCH FIRST FROM MyCursor INTO @B3 SET @S3 = @S3 + @B3 FETCH LAST FROM MyCursor INTO @B3 SET @S3 = @S3 + @B3 SET @S3 = @S3 / 2 PRINT @S3 CLOSE MyCursor DEALLOCATE MyCursor
/* Пример 4: С помощью курсора, сгенерируйте строку вида «Ученики <список фамилий и названий школ, разделенных запятыми> участвовали в олимпиаде» */
DECLARE MyCursor CURSOR SCROLL FOR SELECT Фамилия, Школа FROM Ученики DECLARE @S4 VARCHAR(2000), @F4 VARCHAR(50), @W4 VARCHAR(50) OPEN MyCursor SET @S4 = 'Ученики' FETCH NEXT FROM MyCursor INTO @F4, @W4 WHILE @@FETCH_STATUS = 0 BEGIN SET @S4 = @S4 + ', ' + @F4 + ' из школы "' + @W4 + '"' FETCH NEXT FROM MyCursor INTO @F4, @W4 END SET @S4 = @S4 + ' участвовали на олимпиаде.' PRINT @S4 CLOSE MyCursor DEALLOCATE MyCursor
/* Пример 5: Создайте курсор, содержащий список учеников, с его помощью выведите учеников с четной позицией */
DECLARE MyCursor CURSOR SCROLL FOR SELECT ID, Фамилия, Предмет, Школа, Баллы FROM Ученики OPEN MyCursor FETCH ABSOLUTE 2 FROM MyCursor WHILE @@FETCH_STATUS = 0 BEGIN FETCH RELATIVE 2 FROM MyCursor END CLOSE MyCursor DEALLOCATE MyCursor
/* Пример 6: Создайте курсор, содержащий отсортированный по убыванию баллов список учеников, откройте его, для каждого ученика выведите фамилию, предмет, школу, баллы и разницу баллов с предыдущим учеником */
DECLARE MyCursor CURSOR SCROLL FOR SELECT Фамилия, Предмет, Школа, Баллы FROM Ученики DECLARE @F6 VARCHAR(50) DECLARE @P6 VARCHAR(50) DECLARE @S6 VARCHAR(50) DECLARE @B6 FLOAT DECLARE @OB6 FLOAT = 0 OPEN MyCursor FETCH NEXT FROM MyCursor INTO @F6, @P6, @S6, @B6 WHILE @@FETCH_STATUS = 0 BEGIN SELECT @F6 AS Фамилия, @P6 AS Предмет, @S6 AS Школа, @B6 AS Баллы, ABS(@B6 - @OB6) AS Разница SET @OB6 = @B6 FETCH NEXT FROM MyCursor INTO @F6, @P6, @S6, @B6 END CLOSE MyCursor DEALLOCATE MyCursor