/* Задание 1: Создайте курсор, содержащий отсортированные по баллам фамилии и баллы учеников, откройте его, выведите первую строку, закройте и освободите курсор */
DECLARE MyCursor CURSOR FOR SELECT Фамилия, Баллы FROM Ученики ORDER BY Баллы OPEN MyCursor FETCH MyCursor CLOSE MyCursor DEALLOCATE MyCursor
/* Задание 2: Создайте курсор с прокруткой, содержащий список учеников, откройте его, выведите пятую, предыдущую, с конца четвертую, следующую, первую строку, закройте и освободите курсор */
DECLARE MyCursor CURSOR SCROLL FOR SELECT ID, Фамилия, Предмет, Школа, Баллы FROM Ученики OPEN MyCursor FETCH ABSOLUTE 5 FROM MyCursor FETCH PRIOR FROM MyCursor FETCH ABSOLUTE -4 FROM MyCursor FETCH NEXT FROM MyCursor FETCH FIRST FROM MyCursor CLOSE MyCursor DEALLOCATE MyCursor
/* Задание 3: Создайте курсор с прокруткой, содержащий список учеников, откройте его, выведите последнюю, шесть позиций назад находящуюся, четыре позиций вперед находящуюся строку, закройте и освободите курсор */
DECLARE MyCursor CURSOR SCROLL FOR SELECT ID, Фамилия, Предмет, Школа, Баллы FROM Ученики OPEN MyCursor FETCH LAST FROM MyCursor FETCH RELATIVE -6 FROM MyCursor FETCH RELATIVE 4 FROM MyCursor CLOSE MyCursor DEALLOCATE MyCursor
/* Задание 4: С помощью курсора, вычислите сумму баллов у учеников с наибольшим и наименьшим баллом */
DECLARE MyCursor CURSOR SCROLL FOR SELECT Баллы FROM Ученики ORDER BY Баллы DECLARE @S4 FLOAT = 0, @B4 FLOAT OPEN MyCursor FETCH FIRST FROM MyCursor INTO @B4 SET @S4 = @S4 + @B4 FETCH LAST FROM MyCursor INTO @B4 SET @S4 = @S4 + @B4 PRINT @S4 CLOSE MyCursor DEALLOCATE MyCursor
/* Задание 5: С помощью курсора, сгенерируйте строку вида «Ученики <список фамилий и названий предметов, разделенных запятыми> участвовали в олимпиаде» */
DECLARE MyCursor CURSOR SCROLL FOR SELECT Фамилия, Предмет FROM Ученики DECLARE @S5 VARCHAR(2000), @F5 VARCHAR(50), @P5 VARCHAR(50) OPEN MyCursor SET @S5 = 'Ученики' FETCH NEXT FROM MyCursor INTO @F5, @P5 WHILE @@FETCH_STATUS = 0 BEGIN SET @S5 = @S5 + ', ' + @F5 + ' (' + @P5 + ')' FETCH NEXT FROM MyCursor INTO @F5, @P5 END SET @S5 = @S5 + ' участвовали в олимпиаде.' PRINT @S5 CLOSE MyCursor DEALLOCATE MyCursor
/* Задание 6: Создайте курсор, содержащий список учеников, с его помощью выведите учеников с нечетной позицией */
DECLARE MyCursor CURSOR SCROLL FOR SELECT ID, Фамилия, Предмет, Школа, Баллы FROM Ученики OPEN MyCursor FETCH ABSOLUTE 1 FROM MyCursor WHILE @@FETCH_STATUS = 0 BEGIN FETCH RELATIVE 2 FROM MyCursor END CLOSE MyCursor DEALLOCATE MyCursor
/* Задание 7: Создайте курсор, содержащий отсортированный по убыванию баллов список учеников, откройте его, для каждого ученика выведите фамилию, предмет, школу, баллы и процентное соотношение баллов с предыдущим учеником */
DECLARE MyCursor CURSOR SCROLL FOR SELECT Фамилия, Предмет, Школа, Баллы FROM Ученики ORDER BY Баллы DESC DECLARE @F7 VARCHAR(50) DECLARE @P7 VARCHAR(50) DECLARE @S7 VARCHAR(50) DECLARE @B7 FLOAT DECLARE @OB7 FLOAT = 0 OPEN MyCursor FETCH NEXT FROM MyCursor INTO @F7, @P7, @S7, @B7 WHILE @@FETCH_STATUS = 0 BEGIN SELECT @F7 AS Фамилия, @P7 AS Предмет, @S7 AS Школа, @B7 AS Баллы, CASE WHEN @OB7 = 0 THEN 100 ELSE ROUND((@B7 / @OB7) * 100, 2) END AS [Процентное соотношение] SET @OB7 = @B7 FETCH NEXT FROM MyCursor INTO @F7, @P7, @S7, @B7 END CLOSE MyCursor DEALLOCATE MyCursor